#!/usr/bin/env python

import BaseHTTPServer
import SimpleHTTPServer
SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map['.wasm'] = 'application/wasm'
port = 8000
httpd = BaseHTTPServer.HTTPServer(('localhost', 8000), SimpleHTTPServer.SimpleHTTPRequestHandler)

print "Now serving at http://localhost:8000"

httpd.serve_forever()
